### ISSUE TITLE
Having InteractiveProcess take a &mut Command

### ISSUE THREAD

**Issue by Pat-Lafon** [paulgb/interactive_process#2]
Hello!

Thanks for the crate. This solves the exact niche I was looking for. Do you have an opinion on doing something like https://github.com/Pat-Lafon/interactive_process/commit/c7623a6225953c93c3d2cf82d149e56820ffd4f8 where `InteractiveProcess::new` takes a command by `&mut Command` instead of `Command`? The reason being that if you construct the command like
```rust
    let cmd = Command::new("dune").arg("exec").arg("stub");
```
then `cmd` is a mutable reference to the underlying command object instead of being the owner.

**Comment by Pat-Lafon** [comment]
Actually I found out here you need to create an intermediate binding to avoid the underlying object being dropped like:
```rust
let mut binding = Command::new("dune");
let cmd = binding.arg("exec").arg("stub");
```
So maybe it's not much of an advantage

**Comment by paulgb** [comment]
I agree that taking `&mut Command` is better, even though you're right that it doesn't help much with the ergonomics, unfortunately. It probably won't actually save a copy for most users, but it's more idiomatic than moving the `Command` unnecessarily.

I would merge a PR with your changes.
